/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoleUtilisateur } from '../../models/role-utilisateur';
import { RoleUtilisateurCreateRequest } from '../../models/role-utilisateur-create-request';

export interface CreateRoleUtilisateur$Params {
      body: RoleUtilisateurCreateRequest
}

export function createRoleUtilisateur(http: HttpClient, rootUrl: string, params: CreateRoleUtilisateur$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleUtilisateur>> {
  const rb = new RequestBuilder(rootUrl, createRoleUtilisateur.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RoleUtilisateur>;
    })
  );
}

createRoleUtilisateur.PATH = '/api/v1/rolesUtilisateur';
