/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoleUtilisateur } from '../../models/role-utilisateur';

export interface GetAllRoleUtilisateur$Params {
}

export function getAllRoleUtilisateur(http: HttpClient, rootUrl: string, params?: GetAllRoleUtilisateur$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleUtilisateur>>> {
  const rb = new RequestBuilder(rootUrl, getAllRoleUtilisateur.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RoleUtilisateur>>;
    })
  );
}

getAllRoleUtilisateur.PATH = '/api/v1/rolesUtilisateur';
