/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DepartementReadRequest } from '../../models/departement-read-request';

export interface GetDepartementById$Params {
  id: number;
}

export function getDepartementById(http: HttpClient, rootUrl: string, params: GetDepartementById$Params, context?: HttpContext): Observable<StrictHttpResponse<DepartementReadRequest>> {
  const rb = new RequestBuilder(rootUrl, getDepartementById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DepartementReadRequest>;
    })
  );
}

getDepartementById.PATH = '/api/v1/departements/{id}';
