/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Departement } from '../../models/departement';
import { DepartementCreateRequest } from '../../models/departement-create-request';

export interface UpdateDepartement$Params {
  id: number;
      body: DepartementCreateRequest
}

export function updateDepartement(http: HttpClient, rootUrl: string, params: UpdateDepartement$Params, context?: HttpContext): Observable<StrictHttpResponse<Departement>> {
  const rb = new RequestBuilder(rootUrl, updateDepartement.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Departement>;
    })
  );
}

updateDepartement.PATH = '/api/v1/departements/update/{id}';
