/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Abscence {
  endDate?: string;
  id?: number;
  startDate?: string;
  statut?: boolean;
  typeAbscence?: string;
  user?: User;
}
