/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AbscenceCreateRequest {
  endDate?: string;
  idUser?: number;
  startDate?: string;
  statut?: boolean;
  typeAbscence?: string;
}
