/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Conge {
  description?: string;
  endDate?: string;
  id?: number;
  startDate?: string;
  status?: boolean;
  typeConge?: string;
}
