/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContratCreateRequest {
  dateDebut?: string;
  dateFin?: string;
  description?: string;
  idPoste?: number;
  idTypeContrat?: number;
  idUser?: number;
}
