/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Poste } from '../models/poste';
import { TypeContrat } from '../models/type-contrat';
import { User } from '../models/user';
export interface Contrat {
  dateDebut?: string;
  dateFin?: string;
  description?: string;
  id?: number;
  poste?: Poste;
  typeContrat?: TypeContrat;
  user?: User;
}
