/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeuilleTempsCreateRequest {
  date?: string;
  heureDebutProgramme?: string;
  heureFinProgramme?: string;
  idUser?: number;
}
