/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface FeuilleTemps {
  date?: string;
  heureDebutProgramme?: string;
  heureFinProgramme?: string;
  id?: number;
  user?: User;
}
