/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Formation {
  dateDebut?: string;
  dateFin?: string;
  description?: string;
  domaine?: string;
  duree?: number;
  id?: number;
  statut?: 'NON_DEBUTEE' | 'DEBUTEE' | 'EN_COURS' | 'TERMINER';
  titre?: string;
  type?: string;
  users?: Array<User>;
}
