/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FormationCreateRequest {
  dateDebut?: string;
  dateFin?: string;
  description?: string;
  domaine?: string;
  duree?: number;
  idUser?: number;
  statut?: 'NON_DEBUTEE' | 'DEBUTEE' | 'EN_COURS' | 'TERMINER';
  titre?: string;
  type?: string;
}
