/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Paie {
  heureTravail?: number;
  id?: number;
  montantHeureSup?: number;
  periodePaiementDebut?: string;
  periodePaiementFin?: string;
  salaireBrut?: number;
  salaireNet?: number;
  statut?: boolean;
  tauxHoraire?: number;
  user?: User;
}
