/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaieCreateRequest {
  heureTravail?: number;
  idUser?: number;
  montantHeureSup?: number;
  periodePaiementDebut?: string;
  periodePaiementFin?: string;
  salaireBrut?: number;
  salaireNet?: number;
  statut?: boolean;
  tauxHoraire?: number;
}
