/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Pointage {
  datePointage?: string;
  heurePointage?: string;
  id?: number;
  statut?: 'STATUT_IN' | 'STATUT_OUT';
}
