/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationRequest {
  departementId?: number;
  email: string;
  firstName: string;
  formationId?: number;
  lastName: string;
  password: string;
  roleId?: number;
}
