/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RoleUtilisateur {
  createdDate?: string;
  description?: string;
  id?: number;
  lastModifiedDate?: string;
  title?: string;
}
