/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserCreateRequest {
  email?: string;
  firstName?: string;
  idAbscence?: number;
  idDepartement?: number;
  idFormation?: number;
  idRole?: number;
  lastName?: string;
  password?: string;
  username?: string;
}
