/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Departement } from '../models/departement';
import { Formation } from '../models/formation';
import { GrantedAuthority } from '../models/granted-authority';
import { RoleUtilisateur } from '../models/role-utilisateur';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  birthDate?: string;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  departement?: Departement;
  email?: string;
  enabled?: boolean;
  firstName?: string;
  formations?: Array<Formation>;
  id?: number;
  lastModifiedDate?: string;
  lastName?: string;
  name?: string;
  password?: string;
  userRoles?: Array<RoleUtilisateur>;
  username?: string;
}
