/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pointage } from '../../models/pointage';

export interface CreatePointage$Params {
      body: Pointage
}

export function createPointage(http: HttpClient, rootUrl: string, params: CreatePointage$Params, context?: HttpContext): Observable<StrictHttpResponse<Pointage>> {
  const rb = new RequestBuilder(rootUrl, createPointage.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Pointage>;
    })
  );
}

createPointage.PATH = '/pointage';
