/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pointage } from '../../models/pointage';

export interface UpdatePointage$Params {
  id: number;
      body: Pointage
}

export function updatePointage(http: HttpClient, rootUrl: string, params: UpdatePointage$Params, context?: HttpContext): Observable<StrictHttpResponse<Pointage>> {
  const rb = new RequestBuilder(rootUrl, updatePointage.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Pointage>;
    })
  );
}

updatePointage.PATH = '/pointage/{id}';
