/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TypeContrat } from '../../models/type-contrat';
import { TypeContratCreateRequest } from '../../models/type-contrat-create-request';

export interface CreateTypeContrat$Params {
      body: TypeContratCreateRequest
}

export function createTypeContrat(http: HttpClient, rootUrl: string, params: CreateTypeContrat$Params, context?: HttpContext): Observable<StrictHttpResponse<TypeContrat>> {
  const rb = new RequestBuilder(rootUrl, createTypeContrat.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TypeContrat>;
    })
  );
}

createTypeContrat.PATH = '/auth/typeContrats';
