/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TypeContrat } from '../../models/type-contrat';

export interface GetTypeContratById$Params {
  'typecontrat-id': number;
}

export function getTypeContratById(http: HttpClient, rootUrl: string, params: GetTypeContratById$Params, context?: HttpContext): Observable<StrictHttpResponse<TypeContrat>> {
  const rb = new RequestBuilder(rootUrl, getTypeContratById.PATH, 'get');
  if (params) {
    rb.path('typecontrat-id', params['typecontrat-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TypeContrat>;
    })
  );
}

getTypeContratById.PATH = '/auth/typeContrats/{typecontrat-id}';
