/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TypeContrat } from '../../models/type-contrat';

export interface GetTypeContratByName$Params {
  'typeContrat-name': string;
}

export function getTypeContratByName(http: HttpClient, rootUrl: string, params: GetTypeContratByName$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TypeContrat>>> {
  const rb = new RequestBuilder(rootUrl, getTypeContratByName.PATH, 'get');
  if (params) {
    rb.path('typeContrat-name', params['typeContrat-name'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TypeContrat>>;
    })
  );
}

getTypeContratByName.PATH = '/auth/typeContrats/{typeContrat-name}';
