/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Contrat } from '../../models/contrat';

export interface GetContratById$Params {
  'contrat-id': number;
}

export function getContratById(http: HttpClient, rootUrl: string, params: GetContratById$Params, context?: HttpContext): Observable<StrictHttpResponse<Contrat>> {
  const rb = new RequestBuilder(rootUrl, getContratById.PATH, 'get');
  if (params) {
    rb.path('contrat-id', params['contrat-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Contrat>;
    })
  );
}

getContratById.PATH = '/contrats/{contrat-id}';
