/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Paie } from '../../models/paie';

export interface GetAllPaies$Params {
}

export function getAllPaies(http: HttpClient, rootUrl: string, params?: GetAllPaies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Paie>>> {
  const rb = new RequestBuilder(rootUrl, getAllPaies.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Paie>>;
    })
  );
}

getAllPaies.PATH = '/paies';
