/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Paie } from '../../models/paie';

export interface GetPaie$Params {
  'paie-id': number;
}

export function getPaie(http: HttpClient, rootUrl: string, params: GetPaie$Params, context?: HttpContext): Observable<StrictHttpResponse<Paie>> {
  const rb = new RequestBuilder(rootUrl, getPaie.PATH, 'get');
  if (params) {
    rb.path('paie-id', params['paie-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Paie>;
    })
  );
}

getPaie.PATH = '/paies/{paie-id}';
