/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { PointageControllerService } from './services/pointage-controller.service';
import { FormationControllerService } from './services/formation-controller.service';
import { FeuilleTempsControllerService } from './services/feuille-temps-controller.service';
import { CongeControllerService } from './services/conge-controller.service';
import { DepartementControllerService } from './services/departement-controller.service';
import { UserControllerService } from './services/user-controller.service';
import { PosteControllerService } from './services/poste-controller.service';
import { PaieControllerService } from './services/paie-controller.service';
import { ContratControllerService } from './services/contrat-controller.service';
import { TypeContratControllerService } from './services/type-contrat-controller.service';
import { RoleUtilisateurControllerService } from './services/role-utilisateur-controller.service';
import { AuthenticationService } from './services/authentication.service';
import { AbscenceControllerService } from './services/abscence-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    PointageControllerService,
    FormationControllerService,
    FeuilleTempsControllerService,
    CongeControllerService,
    DepartementControllerService,
    UserControllerService,
    PosteControllerService,
    PaieControllerService,
    ContratControllerService,
    TypeContratControllerService,
    RoleUtilisateurControllerService,
    AuthenticationService,
    AbscenceControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
