/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Poste } from '../../models/poste';

export interface GetPoste$Params {
  'poste-id': number;
}

export function getPoste(http: HttpClient, rootUrl: string, params: GetPoste$Params, context?: HttpContext): Observable<StrictHttpResponse<Poste>> {
  const rb = new RequestBuilder(rootUrl, getPoste.PATH, 'get');
  if (params) {
    rb.path('poste-id', params['poste-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Poste>;
    })
  );
}

getPoste.PATH = '/postes/{poste-id}';
