/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Abscence } from '../../models/abscence';
import { AbscenceCreateRequest } from '../../models/abscence-create-request';

export interface CreateAbsence$Params {
      body: AbscenceCreateRequest
}

export function createAbsence(http: HttpClient, rootUrl: string, params: CreateAbsence$Params, context?: HttpContext): Observable<StrictHttpResponse<Abscence>> {
  const rb = new RequestBuilder(rootUrl, createAbsence.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Abscence>;
    })
  );
}

createAbsence.PATH = '/absences';
