/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FeuilleTemps } from '../../models/feuille-temps';
import { FeuilleTempsCreateRequest } from '../../models/feuille-temps-create-request';

export interface CreateFeuilleDeTemps$Params {
      body: FeuilleTempsCreateRequest
}

export function createFeuilleDeTemps(http: HttpClient, rootUrl: string, params: CreateFeuilleDeTemps$Params, context?: HttpContext): Observable<StrictHttpResponse<FeuilleTemps>> {
  const rb = new RequestBuilder(rootUrl, createFeuilleDeTemps.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FeuilleTemps>;
    })
  );
}

createFeuilleDeTemps.PATH = '/feuilles';
