/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FeuilleTemps } from '../../models/feuille-temps';

export interface GetFeuilleDeTemps$Params {
  id: number;
}

export function getFeuilleDeTemps(http: HttpClient, rootUrl: string, params: GetFeuilleDeTemps$Params, context?: HttpContext): Observable<StrictHttpResponse<FeuilleTemps>> {
  const rb = new RequestBuilder(rootUrl, getFeuilleDeTemps.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FeuilleTemps>;
    })
  );
}

getFeuilleDeTemps.PATH = '/feuilles/{id}';
